apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpdump
  namespace: {{ .Values.ns }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: httpdump
  template:
    metadata:
      labels:
        app: httpdump
    spec:
      containers:
        - name: httpdump
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

---
apiVersion: v1
kind: Service
metadata:
  name: httpdump
  namespace: {{ .Values.ns }}
spec:
  selector:
    app: httpdump
  ports:
    - port: {{ .Values.service.port }}
